### ISSUE TITLE
no comfortable way to close on mac

### ISSUE THREAD

**Issue by vaukalak** [adarrra/d-pad#3]
1 - red button just hides the window (which is fine)
2 - cmd+q and right click on dock + Quit just hides the window (which is not fine)

right now the only way to close the app is from `Force Quit` dialog.

**Comment by adarrra** [comment]
Until  I fix it you can quit from tray icon menu

**Comment by adarrra** [comment]
should be fixed with 4d0cc5587ca465c58ca7dc5f1169948a05024461
